PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
-- CREATE TABLE wedraw_tableword(wordId  INT PRIMARY KEY NOT NULL, wordfield VARCHAR(30) NOT NULL, word VARCHAR(30) NOT NULL);
INSERT INTO "wedraw_tableword" VALUES(1,'IT','bitcoin','bit','coin','rich');
INSERT INTO "wedraw_tableword" VALUES(2,'IT','webapp','web','Charlie','15637');
INSERT INTO "wedraw_tableword" VALUES(3,'IT','blizzard','game company','WoW','HearthStone');
INSERT INTO "wedraw_tableword" VALUES(4,'food','apple','fruit','red','sweet');
INSERT INTO "wedraw_tableword" VALUES(5,'food','banana','fruit','yellow','monkey');
INSERT INTO "wedraw_tableword" VALUES(6,'human','hand','human','body','fingers');
INSERT INTO "wedraw_tableword" VALUES(7,'animal','dog','animal','friendly','loyal');
INSERT INTO "wedraw_tableword" VALUES(8,'animal','hawk','feather','fly','hunter');
INSERT INTO "wedraw_tableword" VALUES(9,'sports','basketball','5vs.5','3-point','YaoMing');
INSERT INTO "wedraw_tableword" VALUES(10,'sports','soccer','most-famous','world-cup','11vs.11');
INSERT INTO "wedraw_tableword" VALUES(11,'IT','chrome','browser','best','google');
INSERT INTO "wedraw_tableword" VALUES(12,'IT','python','language','2vs.3','Django');
INSERT INTO "wedraw_tableword" VALUES(13,'animal','pig','eat','fat','meat');
INSERT INTO "wedraw_tableword" VALUES(14,'food','hotdog','bread','sausage','hot');
INSERT INTO "wedraw_tableword" VALUES(15,'human','foot','human','body','shoe');
INSERT INTO "wedraw_tableword" VALUES(16,'human','eye','face','see','glasses');
INSERT INTO "wedraw_tableword" VALUES(17,'animal','giraffe','tall','Africa','long-neck');
INSERT INTO "wedraw_tableword" VALUES(18,'animal','tiger','strong','hunter','king');
INSERT INTO "wedraw_tableword" VALUES(19,'IT','iphone','mobile','expensive','Jobs');
INSERT INTO "wedraw_tableword" VALUES(20,'sports','football','Gridiron','Quarterback','Steeler');
INSERT INTO "wedraw_tableword" VALUES(21,'superhero','Superman','Marsha','Alien','S');
INSERT INTO "wedraw_tableword" VALUES(22,'superhero','Batman','Marsha','dark','rich');
INSERT INTO "wedraw_tableword" VALUES(23,'superhero','Flash','lighting','run','Iris');
COMMIT;
